### ISSUE TITLE
Troch version conflict

### ISSUE THREAD

**Issue by srdfjy** [JuanFMontesinos/torch_mir_eval#6]
torch_mir_eval needs torch1.9, speechbrain needs torch1.8.1, how to deal with this kind of conflict? Thanks!

**Comment by JuanFMontesinos** [comment]
Soo pytorch has been changing their fft package. Thr default outputs and so on. You just need to use a previous version of the library.
When you use pip you gan define that by doing 
`pip install torch_mir_eval==versionyouneed`

The versions are also in the release package of this repo

**Comment by srdfjy** [comment]
Because the torch_mir_eval 0.3 version has problems with the calculation on the GPU, I need to use the 0.4 version to improve the evaluation speed, but there is a torch version conflict when using speechbrain,I use virtualenv.

**Comment by JuanFMontesinos** [comment]
I am afraid there is not much I can do about it. I just can tell u that issues are like 2 samples in 500. Maybe you can recompute those 2 with cpu? 

The code is roughly the same and the problems arise from pytorch itself.

**Comment by srdfjy** [comment]
@JuanFMontesinos thanks!
